location = /RPC2 {
  include /etc/nginx/fastcgi_params;
  fastcgi_param SCRIPT_FILENAME /rutorrent/app/rpc2.php;
  fastcgi_param RUTORRENT_XMLRPC_ENDPOINT on;
  fastcgi_pass unix:/run/php/php85-fpm.sock;
}
